### ISSUE TITLE
Unable to contribute?

### ISSUE THREAD

**Issue by rampatra** [rohanchandra/type-theme#13]
I tried pushing my commits but `git` wouldn't allow me. Can you please add me as a contributor.

**Comment by rohanchandra** [comment]
Thanks for your interest in contributing.

To contribute changes with Github and Git:
- [Create a fork](https://help.github.com/articles/fork-a-repo/) of the type-theme repo
- Commit changes to your local repo
- Submit a pull request for me to review

More information is available at:

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request/

**Comment by rampatra** [comment]
Thanks for help! Have sent you a pull request, please verify :)
