### ISSUE TITLE
Disabling katex results in a JavaScript error

### ISSUE THREAD

**Issue by busches** [rohanchandra/type-theme#17]
If you set `katex: false` in the `_config.yml` you'll get a JavaScript error with `main.js`. I added the following to `footer.html` to just not include `main.js`, but wasn't sure if people were extending it as well or only using it to enable katex.

```
{% if site.theme.katex %}
<script src="{{ "/js/main.js" | prepend: site.baseurl }}"></script>
{% endif %}
```

If this is an acceptable solution you'd like to merge in, let me know and I can send a PR.

**Comment by rohanchandra** [comment]
Sounds good @busches 

Maybe rename `main.js` to `katex_init.js`

**Comment by busches** [comment]
Sounds good, I'll work on a PR once I get home.

**Comment by rohanchandra** [comment]
Thanks for the fix.
