### ISSUE TITLE
Gists have broken line numbering

### ISSUE THREAD

**Issue by wende** [rohanchandra/type-theme#20]
I don't know how it is possible, but line number bar of gists ( min-width of it) doesn't work properly

![screenshot from 2015-08-26 15 09 24](https://cloud.githubusercontent.com/assets/4634386/9494102/77d5cc68-4c04-11e5-9388-fa3690eb55c7.png)

**Comment by rohanchandra** [comment]
I'll have a look. Is there a link to that post somewhere?

**Comment by wende** [comment]
Nah. I hardcode fixed it. But reproducing is as easy as forking and putting one gist.
