### ISSUE TITLE
Error:  Pygments.rb returned an unacceptable value when attempting to highlight some code.

### ISSUE THREAD

**Issue by karthick-manoharan** [rohanchandra/type-theme#22]
`Jekyll build`

throws this `Error:  Pygments.rb returned an unacceptable value when attempting to highlight some code.`

**Comment by rohanchandra** [comment]
This error is most likely not caused by the theme.

See this issue at https://github.com/jekyll/jekyll/issues/2835

**Comment by karthick-manoharan** [comment]
I bumped on that issue page before opening a issue here. But other themes works fine in the same environment. So mentioned here.

**Comment by rohanchandra** [comment]
Were you using  Pygments for syntax highlighting in the other themes?

**Comment by karthick-manoharan** [comment]
yes. pygments are used.

**Comment by rohanchandra** [comment]
Did you try running `jekyll build` multiple times?

The error can be caused by Pygments timing out.

**Comment by rohanchandra** [comment]
I couldn't reproduce the issue however a temporary fix would be to set the highlighter to Rouge on your local branch, and keeping Pygments for the Github Pages branch (if you're using Github Pages).

The build settings section of  `_config.yml` will look like this:

```
# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
```

**Comment by rohanchandra** [comment]
Github Pages now only supports Rouge, so this theme will also phase out Pygments in favor of Rouge 

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
