### ISSUE TITLE
Jekyll 3.x support

### ISSUE THREAD

**Issue by rohanchandra** [rohanchandra/type-theme#28]
- [x]  Switch to Rouge as highlighter
- [x]  Add `jekyll-paginate` as dependency
- [x]  Check relative permalinks have 3.x support
- [x]  Test on Github Pages
- [x]   Write new documentation for installing dependencies

**Comment by daveharris** [comment]
Hi,
I really like your theme. I'm using it at [dave.harris.org.nz](http://dave.harris.org.nz).
I have some textile posts which I will need to re-write as [Github pages isn't supporting them past 1st May 2106](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0). I was hoping to upgrade my Jekyll to v3.0 at the same time.

Any idea when you would be complete with this?

Thanks,
Dave

**Comment by rohanchandra** [comment]
Hey Dave,

I just updated the theme in 88a87cb1a70a9ad6f1d81ccae412afff9f084025 to use Jekyll 3.0. Glad you like the theme!
