### ISSUE TITLE
Links and avatar should be on the same line

### ISSUE THREAD

**Issue by digitalcraftsman** [rohanchandra/type-theme#29]
Hi @rohanchandra,

on small screen sizes (smartphones, tablets) the links don't stay in the same line as the avatar on the left even if there is enough space. This ways it looks the same on smartphones and desktops.

![](https://raw.githubusercontent.com/digitalcraftsman/hugo-type-theme/master/images/tn.png)

**Comment by rohanchandra** [comment]
Hi @digitalcraftsman 

That's an intentional part of the design for smaller screens. Though you can change the breakpoints in the CSS if you'd like a different look.
