### ISSUE TITLE
Switching Google Fonts to the Mozilla Fira font

### ISSUE THREAD

**Issue by bcooney** [rohanchandra/type-theme#30]
Hi,

I'm unclear on how to remove Google fonts in favor of using an open source font. For example, if I wanted to move to [Firefox's Fira font](https://github.com/mozilla/Fira) without going through Google, how would I do that? I'm in China and the connection to Google is often blocked/extremely slow.

Thanks a lot!

**Comment by rohanchandra** [comment]
If you'd like to use Fira instead, in `_includes/head.html` replace:

```
<!-- Google Fonts -->
{% if site.theme.google_fonts %}
<link href="//fonts.googleapis.com/css?family={{ site.theme.google_fonts }}" rel="stylesheet" type="text/css">
{% endif %}
```

With:

```
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">
```

Then in the `_variables.scss` change `font-family` to your preferred font. For example:

```
// Typography
$font-family-main: 'Fira Sans', Helvetica, Arial, sans-serif;
$font-family-headings: 'Fira Sans', Helvetica, Arial, sans-serif;
```

P.S. All Google Fonts are open-source, so you could self-host the same fonts yourself.

**Comment by bcooney** [comment]
Cheers for that, will load so much faster now! :)
