### ISSUE TITLE
Issue with nested bullet lists

### ISSUE THREAD

**Issue by chmaynard** [rohanchandra/type-theme#31]
Using this theme, the following markdown is not rendered correctly:

```
## Contents
* [Card Matching](#card-matching)
* [Game Play](#game-play)
    * [A Hint](#a-useful-hint)
* [Support](#support)
```

Result:

<img width="203" alt="screen shot 2016-05-14 at 6 21 29 am" src="https://cloud.githubusercontent.com/assets/13698964/15267889/26df4878-199c-11e6-9e21-edd8184c18ca.png">

**Comment by sudoankit** [comment]
Hi, I found a solution by displaying ordered lists outside and unordered lists inside. 
Change the `_global.scss`, with these lines,

```
ol {
  list-style-position: outside;

}

ul {
  list-style-position: inside;
  list-style-type: square;
}
```

Hope it helps!

**Comment by cmaynard** [comment]
Testing now.

**Comment by chmaynard** [comment]
Not much better:

<img width="145" alt="screen shot 2016-06-17 at 8 11 42 pm" src="https://cloud.githubusercontent.com/assets/13698964/16167800/d70d2602-34c7-11e6-83e9-a7993f7f86bd.png">

**Comment by rohanchandra** [comment]
Hi @cmaynard 

This should work:

```
li > ul, li > ol {
    margin-bottom: 0;
    margin-left: 1em;
}
```

**Comment by chmaynard** [comment]
@sudoankit @rohanchandra After applying both sets of rules, I finally got the result I wanted:

<img width="286" alt="screen shot 2016-06-18 at 10 39 09 am" src="https://cloud.githubusercontent.com/assets/13698964/16171613/253e9ae4-3541-11e6-83e4-c05ba8e5a89d.png">

I also commented out the following line to restore the round bullets:

`list-style-type: square;`
