### ISSUE TITLE
Change size of header_text_feature_image

### ISSUE THREAD

**Issue by bfdykstra** [rohanchandra/type-theme#41]
How would I go about changing the size of the displayed image on the first page?

**Comment by rohanchandra** [comment]
Use the [`background-size` property](https://developer.mozilla.org/en/docs/Web/CSS/background-size) on `.call-out`, to specify the size of a background image in CSS.

For example:
```
.call-out {
    background-size: 50%;
}
```

The file you'll need to change is `type-theme/_sass/layouts/_index.scss` or you can use your own custom SCSS file applied on top of Type Theme's styles if you don't want to change the theme's CSS files directly.

**Comment by iMacTia** [comment]
@rohanchandra I would like to use my own custom SCSS file applied on top of Type Theme's styles, however I can't find a way to load my custom file into the site. I suppose the Type Theme should allow this somehow.
Could you explain how to achieve that?
I should point out I'm using the theme as a remote theme, so I can't (and ideally don't want to) change theme files, only add more on top of them

**Comment by rohanchandra** [comment]
@iMacTia Unfortunately, I don't think there's a way to add custom SCSS on top of a remote theme. I would fork the theme and add my own styles instead.

**Comment by iMacTia** [comment]
Thanks for getting back to me @rohanchandra, I'll dig a bit more into it and should I find a solution I'll happily share it with a PR

**Comment by iMacTia** [comment]
@rohanchandra I might have found a nice way to do it and opened #84 to explain it on the README.
