### ISSUE TITLE
Ship theme as a gem

### ISSUE THREAD

**Issue by DirtyF** [rohanchandra/type-theme#42]
This is a nice theme!

Do you plan to provide ability for Jekyll's users to simply add `theme: jekyll-type-theme` and `bundle install` to use your theme?

**Comment by rohanchandra** [comment]
Thanks for the suggestion. I've started converting the theme to a gem Jekyll theme.

**Comment by rohanchandra** [comment]
@DirtyF I've finished a conversion in the gem branch (https://github.com/rohanchandra/type-theme/tree/gem), and I noticed some issues with gem themes, which could make it more inconvenient than the current installation:

- SCSS variables aren't directly editable
- `_config.yml` needs to match the Type Theme one for customization features to work
- GitHub Pages users can't use the gem version

The gem is published at https://rubygems.org/gems/jekyll-theme-type.

For now, I've kept the regular theme as the default.
