### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by chmaynard** [rohanchandra/type-theme#44]
I think it would be useful to have optional subtitles for blog posts in type-theme. I'm not an experienced Ruby developer, so it may take me some time to get this working. Eventually I'll submit my implementation as a pull request. Comments and suggestions welcome.

**Comment by rohanchandra** [comment]
Sounds good @chmaynard. Take a look at https://github.com/rohanchandra/type-theme/blob/master/_layouts/post.html for an example of content that's conditionally rendered:

`{% if page.author %}{{ page.author }}{% endif %}`

Your implementation can do something similar with the subtitle. For example:

`{% if page.subtitle %}<h2 class="subtitle">{{ page.subtitle }}</h2>{% endif %}`

**Comment by chmaynard** [comment]
@rohanchandra Thanks for your suggestion. I changed h2 to h3 and added the new code to ```post.html``` as follows:
```
    {{ page.date | date: "%B %-d, %Y" }}
    {% if page.subtitle %}<h3 class="subtitle">{{ page.subtitle }}</h3>{% endif %}
    {% if page.author %} - {{ page.author }}{% endif %}
```
The front matter would look something like this:
```
---
layout: post
title: Core Memory Concerts
subtitle: Close Encounters of the Best Kind
permalink: house-concerts.html
sitemap: true
---
```
Since you designed the theme, I'd rather let you tweak the code to make subtitles fit in nicely. Thanks!

**Comment by rohanchandra** [comment]
Thanks @chmaynard. I've added the subtitle feature to the theme. 👍
