### ISSUE TITLE
kramdown and KaTeX conflict

### ISSUE THREAD

**Issue by gaberber** [rohanchandra/type-theme#47]
The current implementation of KaTeX in the theme via `/js/katex_init.js` leaves a known conflict between kramdown and KaTeX unaddressed. Kramdown outputs a `%CDATA` markup for some math formulae in its conversion to html. The `%` there chokes KaTeX and all the math thereafter will not be rendered. 

I didn't touch `katex_init.js` but found a rather easy workaround. Instead of using `katex_init.js`, a few lines in `/_includes/footer.html` found in [this kramdown issue](https://github.com/gettalong/kramdown/issues/292) will do (this is also the method suggested on the [official kramdown page](https://kramdown.gettalong.org/math_engine/mathjax.html) for working with KaTeX):

```
{% if site.theme_settings.katex %}
<script src="{{ "/js/jquery-3.2.1.min.js" | prepend: site.baseurl }}"></script>
<script>
   $("script[type='math/tex']").replaceWith(function() {
       var tex = $(this).text();
       // replace() here is due to CDATA wrapper (#224). KaTeX chokes on the % character,
       // which is unfortunate (and should probably be reported).
       return katex.renderToString(tex.replace(/%.*/g, ''), {displayMode: false});
   });

   $("script[type='math/tex; mode=display']").replaceWith(function() {
       var tex = $(this).html();
       // replace() here is due to CDATA wrapper (#224). KaTeX chokes on the % character,
       // which is unfortunate (and should probably be reported).
       return katex.renderToString(tex.replace(/%.*/g, ''), {displayMode: true});
   });
</script>
{% endif %}
```

Two notes: 

- The original author assumed that the `%CDATA` markup only appears in math blocks and not inline math. This is not true. Both inline and block math codes needs stripping away the `%CDATA`, as I've slightly changed here.
- The script requires jQuery. I've put a copy of jQuery in the /js folder.

I'm no web developer but if this makes sense I can make a pull request.

**Comment by rohanchandra** [comment]
I haven't run into this issue, as I haven't used KaTeX much with the theme. A pull request to fix this would be great!

We shouldn't need to add jQuery as it seems we just need a text replacement.

Could you test out editing the `katex_init.js` file and replacing [line 6](https://github.com/rohanchandra/type-theme/blob/master/js/katex_init.js#L6) from this:

```
var textToRender = element.innerText || element.textContent;
```

To this update (which uses your regex):

```
var textToRender = element.innerText || element.textContent;

textToRender = textToRender.replace(/%.*/g, '')
```

This update to `katex_init.js` should fix both inline and block math.

**Comment by gaberber** [comment]
Yup that is the easiest fix out there! We can probably mark this as fixed.
