### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by dovidio** [rohanchandra/type-theme#52]
First of all, thanks for this great theme, I love it! Given that this theme is quite popular I found strange that it does not look good on smaller devices. Has anyone implemented some changes to improve it? If that's not the case I am willing to contribute.

**Comment by rohanchandra** [comment]
Thanks @Cyborg101. There should be some responsive breakpoints to handle things like typography scaling and two-line menus for the smaller screens right now.

Some features haven't been heavily tested on smaller devices, so it would be great to see some enhancements for smaller devices! For example, I've noticed the `.post-nav` needs a breakpoint to reduce padding and split the buttons into two-lines on smaller devices.

Feel free to create a pull request with your changes 👍 If you need any help with the CSS, feel free to ask here.

**Comment by dovidio** [comment]
#54
