### ISSUE TITLE
Gem version / GitHub Pages remote_theme support

### ISSUE THREAD

**Issue by rohanchandra** [rohanchandra/type-theme#59]
The Type Theme gem and GitHub Pages `remote_theme` support is in development.

To use the remote theme:

1. Create a new Jekyll site
2. Add a key-value pair of `remote_theme: rohanchandra/type-theme` to `_config.yml`
3. Switch from `index.md` to `index.html` to enable pagination

Known issues with this development gem are:

- [x] SCSS variables are not editable (fixed by @iMacTia)
- [x] Tags listing (`tags.html`) not available (fixed by @Sylhare)

**Comment by sylhare** [comment]
Allo @rohanchandra ,

For this one, I am not sure what the problem is. 
- Do you want to have the `tags.html` file in your gem?
- For the scss variables, do you mean that the user will have to go in the file which would be in the gem to modify the variables? 

For the "tags problem", I would know a quick fix.

**Comment by rohanchandra** [comment]
@Sylhare That's right. There isn't an easy way to edit the SCSS variables at the moment using the gem version AFAIK.

Regarding the `tags.html` problem, we'd need a way to let the user enable tags (maybe this is something to add to the documentation as well).

Please run a quick test for the `tags.html` using the gem version to check if your fix works 👍 , happy to merge it in.

**Comment by sylhare** [comment]
Oh you mean you've published a new version online of the gem? I have only tried locally so far. And I got the `tags.html` in my unpacked gem.

EDIT: Oh but like, you can't really switch back `hide:true` I mean, you either need to unpack the gem to get the file or you need to have it set to true.
Maybe we could move that "hide" thing into the `_config.yml` ?

**Comment by sylhare** [comment]
Or define a layout for `tags` and `search`, then creating the page would just be creating a `search.html` with this front matter:

```yml
---
layout: tags
---
```

A bit like what is done with the `index.html` page. And for the customisation, well you would not use a gem if you wanted to customize the temlate, you would directly fork/clone the repository.

**Comment by rohanchandra** [comment]
Awesome @Sylhare. Let's move the `hide` variable to the `_config.yml`,  as I think we can read in the variable when setting up the navigation.

**Comment by divayprakash** [comment]
@rohanchandra Only SCSS cars are remaining to fix here?

**Comment by rohanchandra** [comment]
@divayprakash It's been a while since I've worked on this, but the remaining task is to figure out how to expose the SCSS customization of the theme when using the gem version. 

See `_variables.scss` which allows customization of the color and fonts with Google Fonts.

**Comment by rohanchandra** [comment]
The SCSS variables feature for remote themes has been added by @iMacTia, with instructions now in the README!
