### ISSUE TITLE
Adding MathJax

### ISSUE THREAD

**Issue by augusto-garcia** [rohanchandra/type-theme#6]
Hi there,

Your theme is pretty cool, thanks for the good work! I am using it for a course that I am giving (for graduate students): http://augusto-garcia.github.io/Biometria-de-Marcadores/

Is there a way to use MathJax and insert LaTeX equations on posts?

Thanks,
augusto

**Comment by rohanchandra** [comment]
Thank you for your query @augusto-garcia

I have updated the theme to add support for KaTeX. See https://rohanchandra.github.io/project/type/#math-typesetting for more information on adding math equations in your posts.

**Comment by augusto-garcia** [comment]
Thanks very much, @rohanchandra; really useful.
