### ISSUE TITLE
GitHub Pages: The page build completed successfully, but returns error

### ISSUE THREAD

**Issue by link9596** [rohanchandra/type-theme#68]
I used your theme on github, but github has been sending emails to me

**"The page build completed successfully, but return The following warning for ` master ` branch: You are attempting to use a 'Jekyll - theme - type' Jekyll theme, which is not supported by making Pages."**

But I saw your demo was hosted on github. Have you received any email like that?

Can you help me solve this problem?

**Comment by rohanchandra** [comment]
I haven't received an email like that, not too sure what's going on with the GitHub page builds. Could you send me a link to the affected repo if it's public?

I'll keep this issue open to see if other users encounter the issue.

**Comment by link9596** [comment]
[https://link9596.github.io/type-theme/](https://link9596.github.io/type-theme/)
[screenshot](https://link9596.github.io/type-theme/emm.png)

**Comment by boxdox** [comment]
Hello,
You are getting the error as you have uploaded the theme to GitHub pages and have asked GitHub to generate your website.
This is not possible, as GitHub runs with '--safe' flag, meaning that custom themes and plugins aren't supported.
You are supposed to build the site locally and push generated site to GitHub.

**Comment by rohanchandra** [comment]
@link9596 If you're still getting this error, please try this:

1. Open `_config.yml` in the root of your Jekyll site
2. Remove the `theme: jekyll-theme-type` line
