### ISSUE TITLE
gh-pages is out of sync with master

### ISSUE THREAD

**Issue by sylhare** [rohanchandra/type-theme#72]
Allo,

It seems like gh-pages is out of sync with master, it might be a good idea to update it (+ we would see the new features online \o/).
That would maybe help clarify #71 to see if there really is a problem with the github hosting of the new version of the theme.

**Comment by rohanchandra** [comment]
Thanks, I updated the `gh-pages` branch, and removed `theme: jekyll-theme-type` from `_config.yml`.

The GitHub pages demo is working with this config.
