### ISSUE TITLE
Search is not working other than English

### ISSUE THREAD

**Issue by lsjhome** [rohanchandra/type-theme#86]
Current lunr.js/0.7.1/lunr.min.js is only working in English Search. I tried to use 2.3.6 version instead  cos lots of languages are supported but the whole search started not working. 

search.html
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/lunr.js/0.7.1/lunr.min.js" charset="utf-8"></script>
```

**Comment by rohanchandra** [comment]
The API changed in 2.x. Fixed in e28094f839a9a2fecd358c455bc60bf4604b8afc.
