### ISSUE TITLE
Reduce the dependencies to only use actual dependencies

### ISSUE THREAD

**Issue by coltenkrauter** [rohanchandra/type-theme#91]
Context: I started looking into reducing the dependencies that are installed because I was tired of waiting for lengthy builds to complete. 

Currently, the [Gemfile](https://github.com/rohanchandra/type-theme/blob/6b7ad26005ef08d361e03148f01fc03ab100c3dc/Gemfile) contains the following which will install ~85 gems which takes several seconds.

```ruby
# Gemfile - as of 9/14/2019
source "https://rubygems.org"
gem 'github-pages', group: :jekyll_plugins
```

If instead, you specify the actually required gems, you can install ~5 gems which is tremendously faster and should provide the same results. 

```ruby
# Gemfile - a much more efficient method
source "https://rubygems.org"
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "rouge"
  gem "kramdown-parser-gfm"
end
```

This is what I am doing and it is working great. If you were to run into any dependency issues, you could simply add --trace to the build command and then add whatever was being complained about (assuming it is a gem) to the Gemfile. 

For example, if the error was, 
```red
/usr/gem/gems/jekyll-4.0.0/lib/jekyll/converters/markdown/kramdown_parser.rb:53:in `require': cannot load such file -- kramdown-parser-gfm (LoadError)
```
Then you would simply add *gem "kramdown-parser-gfm"* to the Gemfile, as I have done.

By the way, I really like what you have done here.

**Comment by coltenkrauter** [comment]
I will note that I am not using jekyll serve in order to serve the site - I am using nginx in a docker container. So you may need a few more dependencies than I listed, but I noticed several other unnecessary themes were being installed. It is probably best to list the dependencies explicitly. 😃

**Comment by rohanchandra** [comment]
Thanks for bringing this up.

For development purposes, I'd prefer to keep my environment in sync with GitHub Pages, since this is where this theme is mostly used.

> Context: I started looking into reducing the dependencies that are installed because I was tired of waiting for lengthy builds to complete.

Have you considered creating your own Docker image, which you can upload or build using a service like [Docker Hub](https://hub.docker.com/), with the dependencies pre-installed?

**Comment by coltenkrauter** [comment]
Certainly - I appreciate your speedy response. 
I completely understand where you are coming from. 

> Have you considered creating your own Docker image, which you can upload or build using a service like Docker Hub, with the dependencies pre-installed?

A similar solution has crossed my mind. I plan on investigating a solution like that at some point, but my initial research makes me think it will be somewhat complex. 

I sort of wish that the Jekyll build step (or bundle install) could be broken into two steps, 1 for installing dependencies and one for rendering the Jekyll site (templates and stuff) because then I could take advantage of docker caching. I do think this is possible, but again, my limited knowledge of Jekyll makes it seem complex.

**Comment by rohanchandra** [comment]
> A similar solution has crossed my mind. I plan on investigating a solution like that at some point, but my initial research makes me think it will be somewhat complex.

Have a look at using a `Dockerfile`, it's likely only a couple lines of configuration to set-up ([examples](https://github.com/search?l=Dockerfile&p=1&q=%22bundle+install%22+%22Jekyll%22&type=Code)).

If you're using Docker Hub, you can also set it to automatically build and upload the image for you whenever you push to the repo with the `Dockerfile`.

> I sort of wish that the Jekyll build step (or bundle install) could be broken into two steps, 1 for installing dependencies and one for rendering the Jekyll site (templates and stuff) because then I could take advantage of docker caching. I do think this is possible, but again, my limited knowledge of Jekyll makes it seem complex.

Does `bundle install` then `jekyll build` not work?

**Comment by coltenkrauter** [comment]
I appreciate the suggestion with Dockerhub - I actually have a private registry set up so I may do something like that... 

> Does bundle install then jekyll build not work?

I hadn't tried that.... it totally works! Thank you for the suggestion! 
My builds were 50+ seconds. Now they are less than 30 seconds thanks to docker caching (of course the very first build takes a little longer) - I am very happy with that. 🎉 

This is my current Dockerfile,

```
# Stage 1
FROM jekyll/jekyll as jekyll

WORKDIR /app

COPY Gemfile .

RUN chown -R jekyll:jekyll /app

RUN bundle install

COPY . .

RUN chown -R jekyll:jekyll /app

RUN jekyll build --trace

# Stage 2
FROM nginx

COPY --from=jekyll /app/_site /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
```

**Comment by rohanchandra** [comment]
Great! Glad to hear that worked.
