### ISSUE TITLE
Fresh fork does not work

### ISSUE THREAD

**Issue by HermesMarc** [rohanchandra/type-theme#96]
I really like this theme and forked it with the goal to use it for my [github page](https://hermesmarc.github.io/). 

Right now it unfortunately seems that, out of the gate, it does render as intended. 
I have little to no experience with html or CSS as of yet, so I am not sure if this is only due to a minor problem that can be fixed easily or whether this would require more work (Which yould probably mean that I will keep looking for another template to use).

Any comments or help are very welcome!

**Comment by rohanchandra** [comment]
Hi @HermesMarc, after forking the theme, be sure to update your `_config.yml` (https://github.com/rohanchandra/type-theme/blob/master/_config.yml#L2-L3) to match your GitHub Pages URL:

```yml
baseurl: ""
url: "https://hermesmarc.github.io"
```
